Repository Droids-Stock-Trader/Stock_Trader, pull requests merged in 2022-10, with the labels that each got.

#3 TD-45-env
  README.md
  config.py
Labels: enhancement

#4 TD-44 news listing
  app/models/__init__.py
  app/models/_development_data.py
  app/templates/media/_news_listing.html
Labels: enhancement

#6 TD-27 Added documentation to app/auth
  app/auth/forms.py
  app/auth/routes.py
Labels: documentation

#7 TD-6 calls _news_listing.html to display articles
  app/media/routes.py
  app/templates/media/headlines.html
Labels: enhancement

#5 TD-15 News Class Database Table
  app/models/__init__.py
  app/models/news.py
  migrations/versions/ee9463d53f15_news_table.py
  stocktrader.py
Labels: enhancement

#8 TD-16 Preferences validation
  app/settings/forms.py
Labels: enhancement

#9 TD-50 TD-51 License, README, and .gitignore
  .gitignore
  LICENSE
  README.md
Labels: bug, documentation

#13 TD-52 TD-48 Implemented News Back End
  README.md
  app/media/routes.py
  app/models/news.py
  app/models/user.py
  app/templates/errors/404.html
  app/templates/errors/500.html
  app/templates/media/_news_listing.html
  app/templates/media/headlines.html
  config.py
Labels: enhancement

#10 TD-14 Developed history class
  app/models/__init__.py
  app/models/history.py
  app/models/user.py
  migrations/versions/1cf42b66d1b0_created_history_class_and_associated_.py
Labels: enhancement

#12 Pulled logic from validation into its own module
  app/auth/forms.py
  app/settings/forms.py
  app/validation/__init__.py
  app/validation/form_validation.py
Labels: enhancement

#11 TD-28 errors documentation
  app/errors/handlers.py
  stocktrader.py
Labels: documentation
